# Generated by Django 2.1.5 on 2019-02-24 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdmsoro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='permintaanresume',
            name='manual_bukis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manualorder',
            name='permintaan_resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdmsoro.PermintaanResume'),
        ),
    ]
