# Generated by Django 2.1.5 on 2019-02-25 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdmsoro', '0002_auto_20190224_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualorder',
            name='permintaan_resume',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cdmsoro.PermintaanResume'),
        ),
    ]
