# Generated by Django 2.1.5 on 2019-02-26 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdmsoro', '0003_auto_20190225_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permintaanresume',
            name='pic',
            field=models.CharField(max_length=100),
        ),
    ]
