# Generated by Django 2.1.5 on 2019-02-28 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0004_auto_20190226_1205'),
        ('cdmsoro', '0004_auto_20190226_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualOrderSoro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('order_type', models.CharField(choices=[('SO', 'ISOLIR'), ('RO', 'RESUME')], max_length=2)),
                ('keterangan', models.TextField(blank=True, max_length=500)),
                ('order_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masterdata.Order')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.Circuit')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
