# Generated by Django 2.1.5 on 2019-04-09 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdmsoro', '0005_manualordersoro'),
    ]

    operations = [
        migrations.AddField(
            model_name='permintaanresume',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='permintaanresume',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permin_bukis', to='masterdata.Circuit'),
        ),
    ]
