# Generated by Django 2.1.5 on 2019-04-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdmsoro', '0007_auto_20190410_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='validation',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='validation',
            name='message',
            field=models.TextField(default='Approved!', max_length=500),
        ),
    ]
