# Generated by Django 2.1.5 on 2019-04-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdmsoro', '0008_auto_20190410_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='permintaanresume',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Rejected'), (2, 'Approved'), (3, 'Process Validation')], default=3),
        ),
    ]
