# Generated by Django 2.1.5 on 2019-04-12 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdmsoro', '0010_auto_20190411_1001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permintaanresume',
            options={'ordering': ['-update', '-status']},
        ),
    ]
