# Generated by Django 2.2 on 2019-12-19 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdmsoro', '0011_auto_20190412_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='permintaanresume',
            name='abandoned',
            field=models.BooleanField(default=False),
        ),
    ]
