# Generated by Django 2.1.5 on 2019-02-26 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0004_auto_20190226_1205'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('due_date', models.DateField()),
                ('create_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coltarget_creator', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coltarget_customer', to='masterdata.Customer')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
