# Generated by Django 2.1.5 on 2019-03-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_avidenttargetcol'),
    ]

    operations = [
        migrations.AddField(
            model_name='avidenttargetcol',
            name='message',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
