# Generated by Django 2.1.5 on 2019-03-11 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0008_auto_20190309_0619'),
        ('collection', '0005_avidenttargetcol_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('period', models.DateField()),
                ('piutang', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('td_tagih', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colsegment', to='masterdata.Segment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
