# Generated by Django 2.1.5 on 2019-03-27 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection', '0009_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(max_length=2000)),
                ('approve', models.BooleanField(default=False)),
                ('create_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='approval_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='coltarget',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='validation',
            name='create_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='validate_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='avidenttargetcol',
            name='message',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='validation',
            name='msg',
            field=models.TextField(max_length=2000),
        ),
        migrations.AddField(
            model_name='approval',
            name='validation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.Validation'),
        ),
    ]
