# Generated by Django 2.1.5 on 2019-03-28 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0010_auto_20190327_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='validation',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='approval',
            name='validation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.Validation'),
        ),
    ]
