# Generated by Django 2.1.5 on 2019-04-02 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0011_auto_20190328_1113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='validation',
            options={'ordering': ['-timestamp']},
        ),
    ]
