# Generated by Django 2.1.5 on 2019-01-27 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_order_closed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circuit',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-timestamp']},
        ),
    ]
