# Generated by Django 2.1.5 on 2019-03-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0004_auto_20190226_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
