# Generated by Django 2.1.5 on 2019-03-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0005_customer_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='has_target',
            field=models.BooleanField(default=False),
        ),
    ]
