# Generated by Django 2.1.5 on 2019-03-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0008_auto_20190309_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='saldo',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
    ]
