# Generated by Django 2.1.5 on 2019-03-19 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0010_auto_20190318_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='no_valid',
            field=models.BooleanField(default=False),
        ),
    ]
