# Generated by Django 2.1.5 on 2019-03-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0011_customer_no_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
