# Generated by Django 2.1.5 on 2019-03-28 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0013_auto_20190327_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgTaskUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('typetask', models.CharField(choices=[('BJT', 'BJT UPDATE'), ('RSO', 'RECORD ORDER'), ('STA', 'STATUS ORDER')], max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
