# Generated by Django 2.1.5 on 2019-04-10 03:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0014_backgtaskupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='order_label',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Tunggakan'), (2, 'End Contract')], default=1),
        ),
    ]
