# Generated by Django 2.1.5 on 2019-04-12 06:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0016_customer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dbcreate_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='backgtaskupdate',
            name='typetask',
            field=models.CharField(choices=[('BJT', 'BJT UPDATE'), ('RSO', 'RECORD ORDER'), ('STA', 'STATUS ORDER'), ('CSO', 'SO CONTRACT')], max_length=3),
        ),
    ]
