# Generated by Django 2.1.5 on 2019-04-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0017_auto_20190412_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_create_date',
        ),
        migrations.AddField(
            model_name='order',
            name='dbcreate_by',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
