# Generated by Django 2.2 on 2019-10-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0021_order_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='is_lock',
            field=models.BooleanField(default=False),
        ),
    ]
