# Generated by Django 2.2 on 2019-09-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputKoreksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('segmen', models.CharField(max_length=6)),
                ('sbf_account', models.CharField(max_length=8)),
                ('bp_number', models.CharField(max_length=8)),
                ('customer_nm', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('sid', models.CharField(max_length=40)),
                ('wb', models.CharField(max_length=10)),
                ('periode', models.CharField(max_length=6)),
                ('amount', models.PositiveIntegerField()),
                ('keterangan', models.CharField(max_length=2)),
                ('sudah_input_ncx', models.BooleanField(default=False)),
                ('last_order', models.CharField(max_length=15)),
                ('type_last_order', models.CharField(max_length=2)),
                ('status_order', models.CharField(max_length=50)),
                ('abonemen', models.PositiveIntegerField()),
                ('per_last_biling', models.CharField(max_length=6)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
