# Generated by Django 2.2 on 2019-09-25 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koreksi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputkoreksi',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Waiting Validation'), (2, 'Valid'), (3, 'Invalid')], default=1, editable=False),
        ),
    ]
