# Generated by Django 2.2 on 2019-09-25 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koreksi', '0002_inputkoreksi_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inputkoreksi',
            options={'ordering': ['-timestamp']},
        ),
    ]
