# Generated by Django 2.2 on 2019-09-25 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koreksi', '0003_auto_20190925_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputkoreksi',
            name='error_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inputkoreksi',
            name='validate',
            field=models.BooleanField(default=False),
        ),
    ]
