# Generated by Django 2.2 on 2019-09-25 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0021_order_publish'),
        ('koreksi', '0004_auto_20190925_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputkoreksi',
            name='customer_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='koreksi', to='masterdata.Customer'),
        ),
    ]
