# Generated by Django 2.2 on 2019-09-25 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koreksi', '0006_auto_20190925_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentImportTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('doc', models.FileField(upload_to='document/template/')),
                ('is_valid', models.BooleanField(default=False)),
            ],
        ),
    ]
