# Generated by Django 2.2 on 2019-10-01 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koreksi', '0007_documentimporttemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputkoreksi',
            name='wb',
        ),
        migrations.AddField(
            model_name='inputkoreksi',
            name='bandwidth',
            field=models.CharField(blank=True, max_length=10, verbose_name='Bandwidth'),
        ),
        migrations.AddField(
            model_name='inputkoreksi',
            name='layanan',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='inputkoreksi',
            name='abonemen',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inputkoreksi',
            name='last_order',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='inputkoreksi',
            name='per_last_biling',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='inputkoreksi',
            name='status_order',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='inputkoreksi',
            name='type_last_order',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
