# Generated by Django 2.1.5 on 2019-01-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram_user',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
