# Generated by Django 2.1.5 on 2019-03-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_profile_fbcc'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='multiple',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
