# Generated by Django 2.1.5 on 2019-03-27 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_profile_multiple'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.CharField(choices=[('OF', 'Officer'), ('MG', 'Manager')], default='OF', max_length=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='superior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker', to='userprofile.Profile'),
        ),
    ]
