# Generated by Django 2.1.5 on 2019-04-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20190327_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='group',
            field=models.CharField(choices=[('VD', 'Validator'), ('EC', 'Contract Executor'), ('EX', 'Executor'), ('CU', 'Customer')], default='CU', max_length=2),
        ),
    ]
