# Generated by Django 2.2 on 2019-12-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20190411_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name_alias',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
